/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  env: {
    NEXT_PUBLIC_LOGIN: process.env.NEXT_PUBLIC_LOGIN,
    NEXT_PUBLIC_SIGNUP: process.env.NEXT_PUBLIC_SIGNUP,
    NEXT_PUBLIC_LOGOUT: process.env.NEXT_PUBLIC_LOGOUT,
    NEXT_PUBLIC_RECOVERY: process.env.NEXT_PUBLIC_RECOVERY,
    NEXT_PUBLIC_LIST: process.env.NEXT_PUBLIC_LIST,
    NEXT_PUBLIC_SETTINGS: process.env.NEXT_PUBLIC_SETTINGS,
    NEXT_PUBLIC_MFA: process.env.NEXT_PUBLIC_MFA,
    NEXT_PUBLIC_TOGGLETOTP: process.env.NEXT_PUBLIC_TOGGLETOTP,
    NEXT_PUBLIC_CHANGE_PASSWORD: process.env.NEXT_PUBLIC_CHANGE_PASSWORD,
    NEXT_PUBLIC_BAN: process.env.NEXT_PUBLIC_BAN,
    NEXT_PUBLIC_DELETE: process.env.NEXT_PUBLIC_DELETE,
    NEXT_PUBLIC_VERIFY: process.env.NEXT_PUBLIC_VERIFY,
    NEXT_PUBLIC_GET_PROFILE: process.env.NEXT_PUBLIC_GET_PROFILE,
    NEXT_PUBLIC_UPDATE_PROFILE: process.env.NEXT_PUBLIC_UPDATE_PROFILE,
    NEXT_PUBLIC_CREATE: process.env.NEXT_PUBLIC_CREATE,
    NEXT_PUBLIC_REMOVE_BAN: process.env.NEXT_PUBLIC_REMOVE_BAN,
    NEXT_PUBLIC_SWITCH_ROLE: process.env.NEXT_PUBLIC_SWITCH_ROLE,
    NEXT_PUBLIC_APPLICATIONS: process.env.NEXT_PUBLIC_APPLICATIONS,
  },
};

module.exports = nextConfig;
